server:
  port: 8761
eureka:
  instance:
    hostname: localhost
  client:
    fetch-registry: false
    register-with-eureka: false

#eureka.client.service-url.defaultZone: http://localhost:8761/eureka